version: "3"

services:
  nginx:
    ports:
      - "80:80"

# Uncomment if you want to expose MySQL port 3306 outside of Docker
#  mysql:
#    ports:
#      - "3306:3306"

#  beam:
#    environment:
#      XDEBUG_CONFIG: "client_host=10.254.254.254"
#      PHP_IDE_CONFIG: "serverName=beam.remp.press"
#
#    extra_hosts:
#      - "sso.remp.press:172.17.0.1" # This is how Beam container knows that sso.remp.press is running/exposed on the Docker host machine